# Generated by Django 5.2.8 on 2025-11-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='measurements',
        ),
        migrations.AddField(
            model_name='order',
            name='measurement_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
